export const TEAMS = [
  { id: 'red',    name: 'Red',    color: '#ff3b61', icon: 'ti-crown'    },
  { id: 'blue',   name: 'Blue',   color: '#3d8eff', icon: 'ti-diamond'  },
  { id: 'green',  name: 'Green',  color: '#00e676', icon: 'ti-flame'    },
  { id: 'yellow', name: 'Yellow', color: '#ffd600', icon: 'ti-bolt'     },
  { id: 'purple', name: 'Purple', color: '#c84bff', icon: 'ti-moon'     },
  { id: 'orange', name: 'Orange', color: '#ff7c00', icon: 'ti-cocktail' },
  { id: 'pink',   name: 'Pink',   color: '#ff3cac', icon: 'ti-lips'     },
  { id: 'teal',   name: 'Teal',   color: '#00e5ff', icon: 'ti-sparkle'  },
];

export const DEMO_PLAYERS = [
  { id: 'p1',  name: 'Raj',    team: 'red',    flair: 'Quiz captain' },
  { id: 'p2',  name: 'Mira',   team: 'red',    flair: 'Trivia sniper' },
  { id: 'p3',  name: 'Jordan', team: 'red',    flair: 'Buzzer happy' },
  { id: 'p4',  name: 'Sam',    team: 'blue',   flair: 'Lore keeper' },
  { id: 'p5',  name: 'Reese',  team: 'blue',   flair: 'Karaoke kid' },
  { id: 'p6',  name: 'Finn',   team: 'green',  flair: 'Songpop champ' },
  { id: 'p7',  name: 'Zoe',    team: 'green',  flair: 'Pop culture phd' },
  { id: 'p8',  name: 'Ben',    team: 'yellow', flair: 'Dark horse' },
  { id: 'p9',  name: 'Talia',  team: 'yellow', flair: 'Chaotic good' },
  { id: 'p10', name: 'Alex',   team: 'purple', flair: 'Gossip encyclopedia' },
  { id: 'p11', name: 'Noor',   team: 'purple', flair: 'Stats nerd' },
  { id: 'p12', name: 'Kai',    team: 'orange', flair: 'Dark horse' },
  { id: 'p13', name: 'Lou',    team: 'orange', flair: 'Late joiner' },
  { id: 'p14', name: 'Indy',   team: 'pink',   flair: 'Rumor machine' },
  { id: 'p15', name: 'River',  team: 'pink',   flair: 'Streaker' },
  { id: 'p16', name: 'Maya',   team: 'teal',   flair: 'The vibes' },
  { id: 'p17', name: 'Elliot', team: 'teal',   flair: 'Late bloomer' },
];

export const DEMO_TEAM_SCORES = {
  red: 10100, blue: 7400, green: 9700, yellow: 4900,
  purple: 8200, orange: 3600, pink: 7000, teal: 5000,
};

export const TRIVIA_QS = [
  {
    category: 'Steve · Origins', worth: 1000,
    text: "What was Steve's very first concert?",
    answers: ["Spice Girls (age 8)", "Nickelback (age 13)", "Green Day (age 15)", "Shania Twain (age 11)"],
    correct: 3,
    fact: "Held it together until the encore, then cried through 'You're Still the One'.",
  },
  {
    category: 'Steve · Era', worth: 1000,
    text: "Which year was Steve born?",
    answers: ["1982", "1984", "1985", "1986"],
    correct: 2,
    fact: "Same year Microsoft Windows 1.0 shipped. Coincidence? Probably.",
  },
  {
    category: 'Steve · Karaoke', worth: 1500,
    text: "Steve's go-to karaoke closer is…",
    answers: ["Bohemian Rhapsody", "Man! I Feel Like a Woman", "Don't Stop Believin'", "Total Eclipse of the Heart"],
    correct: 1,
    fact: "Bonus points for the wig reveal.",
  },
  {
    category: 'Steve · Trivia', worth: 1000,
    text: "Steve's first real job was…",
    answers: ["Movie theatre usher", "Lifeguard", "Record store clerk", "Paperboy"],
    correct: 2,
    fact: "Allegedly hid all the good vinyls under the counter.",
  },
  {
    category: 'Steve · Confession', worth: 2000,
    text: "Which of these has Steve actually done?",
    answers: ["Opened for a drag queen", "Run a half marathon hungover", "Been on local news", "All of the above"],
    correct: 3,
    fact: "And the drag queen signed the finisher's medal.",
  },
];

export const CELEB_ROUNDS = [
  {
    name: "Timothée Chalamet",
    initials: "TC", hue: '#3d8eff',
    hint: "French-American actor. Bone structure could cut glass.",
    tags: ['Actor', 'Gen Z icon', 'Cheekbones'],
    answer: 'twink',
    reveal: "Certified twink. The internet made it official in 2019.",
    trueTally: { twink: 78, lesbian: 22 },
  },
  {
    name: "Kristen Stewart",
    initials: "KS", hue: '#ff3cac',
    hint: "You know her from Twilight. You know her vibe from everything since.",
    tags: ['Actor', 'Indie darling', 'Flannel'],
    answer: 'lesbian',
    reveal: "Out and proud since 2017. Flannel optional.",
    trueTally: { twink: 14, lesbian: 86 },
  },
  {
    name: "Harry Styles",
    initials: "HS", hue: '#c84bff',
    hint: "Ex-boy-bander turned solo icon. Known for bold fashion choices.",
    tags: ['Musician', 'Fashion icon', 'Fishnet era'],
    answer: 'twink',
    reveal: "Twink-adjacent at minimum. The fishnet era settled it.",
    trueTally: { twink: 64, lesbian: 36 },
  },
  {
    name: "Kate McKinnon",
    initials: "KM", hue: '#ff3cac',
    hint: "SNL legend. Has played every gay icon at least once.",
    tags: ['Comedian', 'SNL', 'Gay icon'],
    answer: 'lesbian',
    reveal: "Out since forever. Patron saint of this game.",
    trueTally: { twink: 8, lesbian: 92 },
  },
  {
    name: "Billy Porter",
    initials: "BP", hue: '#ffd600',
    hint: "Pose star. Wore a tuxedo gown to the Oscars and nobody blinked.",
    tags: ['Actor', 'Singer', 'Fashion'],
    answer: 'twink',
    reveal: "The tuxedo gown at the Oscars said everything.",
    trueTally: { twink: 72, lesbian: 28 },
  },
  {
    name: "Janelle Monáe",
    initials: "JM", hue: '#00e676',
    hint: "Musician and actor. Dirty Computer changed things.",
    tags: ['Musician', 'Actor', 'Pansexual icon'],
    answer: 'lesbian',
    reveal: "Pansexual and free. Dirty Computer was the coming out we needed.",
    trueTally: { twink: 20, lesbian: 80 },
  },
  {
    name: "Troye Sivan",
    initials: "TS", hue: '#3d8eff',
    hint: "Australian pop star. Rush was an era.",
    tags: ['Musician', 'Australian', 'Pop star'],
    answer: 'twink',
    reveal: "Rush was basically the twink national anthem.",
    trueTally: { twink: 88, lesbian: 12 },
  },
  {
    name: "Tessa Thompson",
    initials: "TT", hue: '#ff3cac',
    hint: "Valkyrie in the MCU. Confirmed the vibes herself.",
    tags: ['Actor', 'MCU', 'Valkyrie'],
    answer: 'lesbian',
    reveal: "Valkyrie was queer-coded for a reason. Thompson confirmed the vibes.",
    trueTally: { twink: 18, lesbian: 82 },
  },
  {
    name: "Lil Nas X",
    initials: "LNX", hue: '#ff7c00',
    hint: "Old Town Road to Montero. The Grammys performance said it all.",
    tags: ['Musician', 'Rapper', 'Grammys'],
    answer: 'twink',
    reveal: "Gave Satan a lap dance at the Grammys. Peak twink behavior.",
    trueTally: { twink: 82, lesbian: 18 },
  },
  {
    name: "Hayley Kiyoko",
    initials: "HK", hue: '#ff3cac',
    hint: "Singer known as Lesbian Jesus. Not a nickname she disputes.",
    tags: ['Musician', 'Lesbian Jesus', 'Pop'],
    answer: 'lesbian',
    reveal: "Lesbian Jesus herself. No debate.",
    trueTally: { twink: 4, lesbian: 96 },
  },
];

export const LIPSYNC_SONGS = [
  { title: 'Padam Padam',                artist: 'Kylie Minogue' },
  { title: 'Man! I Feel Like a Woman',   artist: 'Shania Twain' },
  { title: 'Dancing Queen',              artist: 'ABBA' },
  { title: 'I Will Survive',             artist: 'Gloria Gaynor' },
  { title: 'Toxic',                      artist: 'Britney Spears' },
  { title: 'Bad Romance',                artist: 'Lady Gaga' },
  { title: 'Mr. Brightside',             artist: 'The Killers' },
  { title: 'Total Eclipse of the Heart', artist: 'Bonnie Tyler' },
];

export const ROOM_CODE = 'TEA40';
export const JOIN_URL  = 'steave-40.fly.dev';
